<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Presensi_rekap extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Presensi_rekap_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template', 'presensi/presensi_rekap');
       
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Presensi_rekap_model->json();
    }

    public function read($id)
    {
        $row = $this->Presensi_rekap_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id_presensi' => $row->id_presensi,
                'id_karyawan' => $row->id_karyawan,
                'tanggal' => $row->tanggal,
                'waktu_masuk' => $row->waktu_masuk,
                'waktu_keluar' => $row->waktu_keluar,
            );
            $this->template->load('template', 'presensi/presensi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('presensi'));
        }
    }

}
/* End of file Presensi.php */
/* Location: ./application/controllers/Presensi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-16 08:36:54 */
/* http://harviacode.com */